//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр.
    /// </summary>
    // *** Start programmer edit section *** (Регистр CustomAttributes)

    // *** End programmer edit section *** (Регистр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрE", new string[] {
            "КодРегист as \'Код регистра\'",
            "Регистрат as \'Регистрат\'",
            "Период as \'Период\'",
            "Наимен as \'Наименов\'"})]
    [View("РегистрL", new string[] {
            "КодРегист as \'Код регист\'",
            "Наимен as \'Наименование\'",
            "Регистрат as \'Регистрат\'",
            "Период as \'Период\'"})]
    public class Регистр : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодРегист;
        
        private string fРегистрат;
        
        private string fНаимен;
        
        private string fПериод;
        
        // *** Start programmer edit section *** (Регистр CustomMembers)

        // *** End programmer edit section *** (Регистр CustomMembers)

        
        /// <summary>
        /// КодРегист.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.КодРегист CustomAttributes)

        // *** End programmer edit section *** (Регистр.КодРегист CustomAttributes)
        public virtual int КодРегист
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.КодРегист Get start)

                // *** End programmer edit section *** (Регистр.КодРегист Get start)
                int result = this.fКодРегист;
                // *** Start programmer edit section *** (Регистр.КодРегист Get end)

                // *** End programmer edit section *** (Регистр.КодРегист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.КодРегист Set start)

                // *** End programmer edit section *** (Регистр.КодРегист Set start)
                this.fКодРегист = value;
                // *** Start programmer edit section *** (Регистр.КодРегист Set end)

                // *** End programmer edit section *** (Регистр.КодРегист Set end)
            }
        }
        
        /// <summary>
        /// Наимен.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Наимен CustomAttributes)

        // *** End programmer edit section *** (Регистр.Наимен CustomAttributes)
        [StrLen(255)]
        public virtual string Наимен
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Наимен Get start)

                // *** End programmer edit section *** (Регистр.Наимен Get start)
                string result = this.fНаимен;
                // *** Start programmer edit section *** (Регистр.Наимен Get end)

                // *** End programmer edit section *** (Регистр.Наимен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Наимен Set start)

                // *** End programmer edit section *** (Регистр.Наимен Set start)
                this.fНаимен = value;
                // *** Start programmer edit section *** (Регистр.Наимен Set end)

                // *** End programmer edit section *** (Регистр.Наимен Set end)
            }
        }
        
        /// <summary>
        /// Период.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Период CustomAttributes)

        // *** End programmer edit section *** (Регистр.Период CustomAttributes)
        [StrLen(255)]
        public virtual string Период
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Период Get start)

                // *** End programmer edit section *** (Регистр.Период Get start)
                string result = this.fПериод;
                // *** Start programmer edit section *** (Регистр.Период Get end)

                // *** End programmer edit section *** (Регистр.Период Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Период Set start)

                // *** End programmer edit section *** (Регистр.Период Set start)
                this.fПериод = value;
                // *** Start programmer edit section *** (Регистр.Период Set end)

                // *** End programmer edit section *** (Регистр.Период Set end)
            }
        }
        
        /// <summary>
        /// Регистрат.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Регистрат CustomAttributes)

        // *** End programmer edit section *** (Регистр.Регистрат CustomAttributes)
        [StrLen(255)]
        public virtual string Регистрат
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Регистрат Get start)

                // *** End programmer edit section *** (Регистр.Регистрат Get start)
                string result = this.fРегистрат;
                // *** Start programmer edit section *** (Регистр.Регистрат Get end)

                // *** End programmer edit section *** (Регистр.Регистрат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Регистрат Set start)

                // *** End programmer edit section *** (Регистр.Регистрат Set start)
                this.fРегистрат = value;
                // *** Start programmer edit section *** (Регистр.Регистрат Set end)

                // *** End programmer edit section *** (Регистр.Регистрат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрE", typeof(IIS.Test.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрL", typeof(IIS.Test.Регистр));
                }
            }
        }
    }
}
