




CREATE TABLE Заявка (
 primaryKey UUID NOT NULL,
 Текст VARCHAR(255) NULL,
 Состоян VARCHAR(255) NULL,
 Важност VARCHAR(255) NULL,
 НомЗаяв VARCHAR(255) NULL,
 Сотрудник UUID NOT NULL,
 Контрагент UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Регистр (
 primaryKey UUID NOT NULL,
 КодРегист INT NULL,
 Регистрат VARCHAR(255) NULL,
 Наимен VARCHAR(255) NULL,
 Период VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Сотрудник (
 primaryKey UUID NOT NULL,
 Фамил VARCHAR(255) NULL,
 ТабНом VARCHAR(255) NULL,
 НомПасп INT NULL,
 Имя VARCHAR(255) NULL,
 Отчест VARCHAR(255) NULL,
 Серия INT NULL,
 Должности UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Должности (
 primaryKey UUID NOT NULL,
 КодДолж INT NULL,
 Наимен VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Записи (
 primaryKey UUID NOT NULL,
 КодЗаписи VARCHAR(255) NULL,
 НомЗаяв VARCHAR(255) NULL,
 Дата TIMESTAMP(3) NULL,
 КодРегист INT NULL,
 ВремНач VARCHAR(255) NULL,
 ВремОкон VARCHAR(255) NULL,
 Заявка UUID NOT NULL,
 Регистр UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Контрагент (
 primaryKey UUID NOT NULL,
 Контр INT NULL,
 Организ VARCHAR(255) NULL,
 Наимен VARCHAR(255) NULL,
 Договор VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Заявка ADD CONSTRAINT FK1067822e146486fa4b47f3c6fa43eba5d742b19f FOREIGN KEY (Сотрудник) REFERENCES Сотрудник; 
CREATE INDEX Index1067822e146486fa4b47f3c6fa43eba5d742b19f on Заявка (Сотрудник); 

 ALTER TABLE Заявка ADD CONSTRAINT FK14049e0d8312bdadcc14e80511113090938782fa FOREIGN KEY (Контрагент) REFERENCES Контрагент; 
CREATE INDEX Index14049e0d8312bdadcc14e80511113090938782fa on Заявка (Контрагент); 

 ALTER TABLE Сотрудник ADD CONSTRAINT FKcddb0989bfc59f7f8b75feb65c08d7cc7f9c96b0 FOREIGN KEY (Должности) REFERENCES Должности; 
CREATE INDEX Indexcddb0989bfc59f7f8b75feb65c08d7cc7f9c96b0 on Сотрудник (Должности); 

 ALTER TABLE Записи ADD CONSTRAINT FKc91057b6b9a03e9713546470e09337f88605077e FOREIGN KEY (Заявка) REFERENCES Заявка; 
CREATE INDEX Indexc91057b6b9a03e9713546470e09337f88605077e on Записи (Заявка); 

 ALTER TABLE Записи ADD CONSTRAINT FK8a4761ea1debee96d376f84249202d4e3ec7258e FOREIGN KEY (Регистр) REFERENCES Регистр; 
CREATE INDEX Index8a4761ea1debee96d376f84249202d4e3ec7258e on Записи (Регистр); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

